from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_SmallMailer(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Small Mailer - Thanks to use :)")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setSizeIncrement(QtCore.QSize(800, 600))
        MainWindow.setBaseSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, -10, 291, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setIndent(-1)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 20, 151, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 111, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(-10, 0, 821, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(36)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 70, 311, 481))
        self.textEdit.setObjectName("textEdit")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(330, 70, 311, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(330, 50, 191, 21))
        self.label_5.setObjectName("label_5")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(330, 530, 501, 20))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(330, 510, 121, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(330, 160, 221, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(330, 90, 121, 21))
        self.label_8.setObjectName("label_8")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(330, 110, 311, 51))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(330, 460, 81, 21))
        self.label_9.setObjectName("label_9")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(330, 480, 311, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(650, 480, 144, 33))
        self.pushButton.setObjectName("pushButton")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(650, 50, 111, 21))
        self.label_10.setObjectName("label_10")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(650, 70, 141, 391))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(330, 180, 311, 281))
        self.textEdit_3.setObjectName("textEdit_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menudenbingon = QtWidgets.QMenu(self.menubar)
        self.menudenbingon.setObjectName("menudenbingon")
        self.menuGitHub = QtWidgets.QMenu(self.menudenbingon)
        self.menuGitHub.setObjectName("menuGitHub")
        self.menuVK = QtWidgets.QMenu(self.menudenbingon)
        self.menuVK.setObjectName("menuVK")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLINK = QtWidgets.QAction(MainWindow)
        self.actionLINK.setObjectName("actionLINK")
        self.actionLINK_2 = QtWidgets.QAction(MainWindow)
        self.actionLINK_2.setObjectName("actionLINK_2")
        self.menuGitHub.addAction(self.actionLINK)
        self.menuVK.addAction(self.actionLINK_2)
        self.menudenbingon.addAction(self.menuGitHub.menuAction())
        self.menudenbingon.addAction(self.menuVK.menuAction())
        self.menubar.addAction(self.menudenbingon.menuAction())
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Small Mailer"))
        self.label_2.setText(_translate("MainWindow", "by DENBINGON"))
        self.label_3.setText(_translate("MainWindow", "Enter email base: "))
        self.label_4.setText(_translate("MainWindow", "_"*100))
        self.label_5.setText(_translate("MainWindow", "Mail from post:"))
        self.label_6.setText(_translate("MainWindow", "Progress:"))
        self.label_7.setText(_translate("MainWindow", "Enter text or html to post:"))
        self.label_8.setText(_translate("MainWindow", "Title:"))
        self.label_9.setText(_translate("MainWindow", "Sigature:"))
        self.pushButton.setText(_translate("MainWindow", "Начать"))
        self.label_10.setText(_translate("MainWindow", "Status:"))
        self.menudenbingon.setTitle(_translate("MainWindow", "denbingon"))
        self.menuGitHub.setTitle(_translate("MainWindow", "GitHub"))
        self.menuVK.setTitle(_translate("MainWindow", "VK"))
        self.actionLINK.setText(_translate("MainWindow", "LINK"))
        self.actionLINK_2.setText(_translate("MainWindow", "LINK"))
