from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1118, 624)
        MainWindow.setMinimumSize(QtCore.QSize(1118, 624))
        MainWindow.setMaximumSize(QtCore.QSize(1118, 624))
        MainWindow.setSizeIncrement(QtCore.QSize(1118, 624))
        MainWindow.setBaseSize(QtCore.QSize(1118, 624))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget_sklad = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_sklad.setGeometry(QtCore.QRect(0, 40, 624, 531))
        self.tableWidget_sklad.setMinimumSize(QtCore.QSize(624, 300))
        self.tableWidget_sklad.setMaximumSize(QtCore.QSize(624, 585))
        self.tableWidget_sklad.setSizeIncrement(QtCore.QSize(624, 585))
        self.tableWidget_sklad.setBaseSize(QtCore.QSize(624, 585))
        self.tableWidget_sklad.setAcceptDrops(True)
        self.tableWidget_sklad.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget_sklad.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_sklad.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tableWidget_sklad.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.tableWidget_sklad.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidget_sklad.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableWidget_sklad.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_sklad.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_sklad.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget_sklad.setObjectName("tableWidget_sklad")
        self.tableWidget_sklad.setColumnCount(3)
        self.tableWidget_sklad.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_sklad.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_sklad.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_sklad.setHorizontalHeaderItem(2, item)
        self.tableWidget_sklad.horizontalHeader().setVisible(True)
        self.tableWidget_sklad.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_sklad.horizontalHeader().setDefaultSectionSize(148)
        self.tableWidget_sklad.horizontalHeader().setHighlightSections(True)
        self.tableWidget_sklad.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_sklad.verticalHeader().setVisible(True)
        self.tableWidget_sklad.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget_sklad.verticalHeader().setHighlightSections(True)
        self.tableWidget_sklad.verticalHeader().setSortIndicatorShown(False)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Nexa Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(638, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nexa Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tableWidget_ends = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_ends.setGeometry(QtCore.QRect(634, 40, 481, 281))
        self.tableWidget_ends.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_ends.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_ends.setObjectName("tableWidget_ends")
        self.tableWidget_ends.setColumnCount(3)
        self.tableWidget_ends.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ends.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Название")
        self.tableWidget_ends.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ends.setHorizontalHeaderItem(2, item)
        self.tableWidget_ends.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_ends.horizontalHeader().setDefaultSectionSize(150)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(638, 320, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Nexa Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.tableWidget_ordered = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_ordered.setGeometry(QtCore.QRect(634, 350, 481, 271))
        self.tableWidget_ordered.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_ordered.setObjectName("tableWidget_ordered")
        self.tableWidget_ordered.setColumnCount(3)
        self.tableWidget_ordered.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ordered.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ordered.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ordered.setHorizontalHeaderItem(2, item)
        self.tableWidget_ordered.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_ordered.horizontalHeader().setDefaultSectionSize(150)
        self.pushButton_addRow = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_addRow.setGeometry(QtCore.QRect(0, 572, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_addRow.setFont(font)
        self.pushButton_addRow.setObjectName("pushButton_addRow")
        self.pushButton_retry = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_retry.setGeometry(QtCore.QRect(100, 572, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Nexa Light")
        font.setPointSize(12)
        self.pushButton_retry.setFont(font)
        self.pushButton_retry.setObjectName("pushButton_retry")
        self.pushButton_saveXlsx = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_saveXlsx.setGeometry(QtCore.QRect(330, 572, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Nexa Light")
        font.setPointSize(12)
        self.pushButton_saveXlsx.setFont(font)
        self.pushButton_saveXlsx.setObjectName("pushButton_saveXlsx")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 572, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Nexa Light")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(485, 570, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(556, 577, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 572, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(822, 17, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(806, 19, 20, 20))
        self.label_6.setObjectName("label_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(940, 17, 75, 21))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(822, 327, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(940, 327, 75, 21))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(806, 328, 20, 20))
        self.label_7.setObjectName("label_7")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(1020, 17, 75, 21))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(1020, 327, 75, 21))
        self.pushButton_6.setObjectName("pushButton_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1118, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MySort by DENBINGON"))
        item = self.tableWidget_sklad.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Название"))
        item = self.tableWidget_sklad.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Количество"))
        item = self.tableWidget_sklad.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "ID"))
        self.label.setText(_translate("MainWindow", "Склад:"))
        self.label_2.setText(_translate("MainWindow", "Кончилось:"))
        item = self.tableWidget_ends.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_ends.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Количество"))
        self.label_3.setText(_translate("MainWindow", "Заказано:"))
        item = self.tableWidget_ordered.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_ordered.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Название"))
        item = self.tableWidget_ordered.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Количество"))
        self.pushButton_addRow.setText(_translate("MainWindow", "+"))
        self.pushButton_retry.setText(_translate("MainWindow", "Обновить"))
        self.pushButton_saveXlsx.setText(_translate("MainWindow", "Сохранить в XLSX"))
        self.pushButton.setText(_translate("MainWindow", "Сохранить"))
        self.label_4.setText(_translate("MainWindow", "MySort "))
        self.label_5.setText(_translate("MainWindow", "by DENBINGON"))
        self.pushButton_2.setText(_translate("MainWindow", "-"))
        self.label_6.setText(_translate("MainWindow", "№"))
        self.pushButton_3.setText(_translate("MainWindow", "Ок"))
        self.pushButton_4.setText(_translate("MainWindow", "Ок"))
        self.label_7.setText(_translate("MainWindow", "№"))
        self.pushButton_5.setText(_translate("MainWindow", "Заказано все"))
        self.pushButton_6.setText(_translate("MainWindow", "Прибыло все"))
